### ISSUE TITLE
cran release

### ISSUE THREAD

**Issue by jburkhardt** [banboo-data/r4googleads#37]
**To-Dos:**
* [x] Please always write package names, software names and API (application 
programming interface) names in single quotes in title and description. 
e.g: --> 'Google Ads'
* [x] Please write TRUE and FALSE instead of T and F. (Please don't use 'T' or 
'F' as vector names.), e.g.:
   * man/authenticate.Rd
   * man/query_google_ads.Rd
* [x] Please add \value to .Rd files regarding exported methods and explain 
the functions results in the documentation. Please write about the 
structure of the output (class) and also what the output means. (If a 
function does not return a value, please document that too, e.g. 
\value{No return value, called for side effects} or similar)
* [x] Missing Rd-tags:
    * build_handle.Rd: \value
    * googleAdsFields.Rd: \value
    * googleAdsSearch.Rd: \value
    * listAccessibleCustomers.Rd: \value
    * r4googleads-deprecated.Rd: \value
* [x] Missing Rd-tags: queries.Rd: \arguments
* [x] You write information messages to the console that cannot be easily 
suppressed. It is more R like to generate objects that can be used to 
extract the information a user is interested in, and then print() that 
object. Instead of print()/cat() rather use message()/warning() or 
if(verbose)cat(..) (or maybe stop()) if you really have to write text to 
the console. (except for print, summary, interactive functions)

**Comment by jburkhardt** [comment]
@mbannert The `\arguments` tag in man/queries.Rd is missing. This is a CRAN requirement. The functions in R/queries.R do not have function arguments (e.g. `default_search()`). How can we generate the `\arguments` tag for man/queries.Rd with `devtools::document()` or `roxygen2` even though the functions do not have parameters (no `@param`)?

**Comment by mbannert** [comment]
How and where did you encounter these errors. I.e., which version of R did you run on which OS and what check did you run exactly ?

**Comment by mbannert** [comment]
I think we're good to go @jburkhardt :

- R CMD Check via pkgdown / GHA workflow passes (see badge) 
- rhub checks passed on all OSes they tested
- local stuff works stuff

can you confirm and upload to CRAN again (and close this issue)?
